DROP TABLE IF EXISTS "Restaurant" CASCADE;
DROP TABLE IF EXISTS "RestaurantTags" CASCADE;
DROP TABLE IF EXISTS "Tag" CASCADE;
DROP TABLE IF EXISTS "Vote" CASCADE;
DROP TABLE IF EXISTS "Group" CASCADE;
DROP TABLE IF EXISTS "GroupUsers" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
